#ifndef LIFECYCLES_MSGS__MSG__TRANSITION_H_
#define LIFECYCLES_MSGS__MSG__TRANSITION_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>

#define TRANSITION_CREATE 0
#define TRANSITION_CONFIGURE 1
#define TRANSITION_CLEANUP 2
#define TRANSITION_ACTIVATE 3
#define TRANSITION_DEACTIVATE 4
#define TRANSITION_UNCONFIGURED_SHUTDOWN 5
#define TRANSITION_INACTIVE_SHUTDOWN 6
#define TRANSITION_ACTIVE_SHUTDOWN 7
#define TRANSITION_DESTROY 8

#define TRANSITION_ON_CONFIGURE_SUCCESS 10
#define TRANSITION_ON_CONFIGURE_FAILURE 11
#define TRANSITION_ON_CONFIGURE_ERROR 12

#define TRANSITION_ON_CLEANUP_SUCCESS 20
#define TRANSITION_ON_CLEANUP_FAILURE 21
#define TRANSITION_ON_CLEANUP_ERROR 22

#define TRANSITION_ON_ACTIVATE_SUCCESS 30
#define TRANSITION_ON_ACTIVATE_FAILURE 31
#define TRANSITION_ON_ACTIVATE_ERROR 32

#define TRANSITION_ON_DEACTIVATE_SUCCESS 40
#define TRANSITION_ON_DEACTIVATE_FAILURE 41
#define TRANSITION_ON_DEACTIVATE_ERROR 42

#define TRANSITION_ON_SHUTDOWN_SUCCESS 50
#define TRANSITION_ON_SHUTDOWN_FAILURE 51
#define TRANSITION_ON_SHUTDOWN_ERROR 52

#define TRANSITION_ON_ERROR_SUCCESS 60
#define TRANSITION_ON_ERROR_FAILURE 61
#define TRANSITION_ON_ERROR_ERROR 62

#define TRANSITION_CALLBACK_SUCCESS 97
#define TRANSITION_CALLBACK_FAILURE 98
#define TRANSITION_CALLBACK_ERROR 99

typedef struct Transition
{
  uint8_t id;
  char label[32];  // Size determined by the maximum length of the label
} lifecycles_msgs__msg__Transition;

#ifdef __cplusplus
} // extern "C" 
#endif

#endif  // LIFECYCLES_MSGS__MSG__TRANSITION_H_